### ISSUE TITLE
GSoC 2018 Work Plan

### ISSUE THREAD

**Issue by wisn** [wisn/format-preserving-yaml#1]
Google Summer of Code 2018 work plan for Format-Preserving YAML project. This is based on the GSoC 2018 timeline and will be group by evaluation phase milestone. Ordered by its priority.

**NOTE**: This work plan will be dynamically change based on the situation.

### First Evaluation

- [x] Build a Format-Preserving List as an MVP. **Finished partially in the week #1.**
- [ ] Learn BNF Grammar, Lens, Happy, and Parsec.
- [x] Implement the YAML Parser with simple token working in it such as whitespace, newline, comment, and so on.
- [x] Implement the YAML Formatter for a simple token such as whitespace, newline, comment, and so on.
- [ ] Writing some tests.
- [ ] Writing a documentation.

### Second Evaluation

- [ ] Improve the latest YAML Parser.
- [ ] Improve the latest YAML Formatter.
- [ ] Writing some tests.
- [ ] Improve the documentation.
- [ ] Try it out in the real world.

### Final Evaluation

- [ ] Improve the latest YAML Parser.
- [ ] Improve the latest YAML Formatter.
- [ ] Writing some tests.
- [ ] Improve the documentation.
- [ ] Try it out in the real world.
- [ ] Finishing it up.

**Comment by wisn** [comment]
Based on the [YAML Processing Overview](http://yaml.org/spec/1.2/spec.html#id2762107), there are three steps to contruct the YAML into a native data structure. Parse, compose, and contruct. Could I make something like `Format.YAML.Parser`, `Format.YAML.Composer`, and `Format.YAML.Contructor`? I think this is library will be more modular and much easier to handle [Floading Failure Point](http://yaml.org/spec/1.2/spec.html#id2767381).

I'm now experimenting with Parsec and try to implement the **parser** based on YAML [Production Naming Convention](http://yaml.org/spec/1.2/spec.html#id2770517) which is started by the simplest one such as `s-` production that process whitespace, tab, comment, and so on. Any thoughts?

Ah, for the **correctness** part, is testing with HSpec enough? When heard something like "correctness", I always think about something like formal verification.

Cc @jaspervdj @NorfairKing

**Comment by jaspervdj** [comment]
@wisn Those three steps sound fair for a conventional application where you are just loading YAML but I don't think you should stick to these too much for this project.

You should try to develop the parser and the datastructure that is as close to the YAML specification at the same time.  The naming convention sounds like a good way to name your functions.

The composer and constructor parts can be ignored for now -- they are passes over the YAML datastructure which we'll look at later.

For correctness, I think it is important to keep some tests as you develop the project.  HSpec sounds find and we should do property testing as well.  Formal verification is not necessary.

Please try to commit as early and frequent as possible, so we can help out.  If you have parts that don't work quite yet, try to do these in a branch and send a pull request against your own repository, that way we can see what is happening and point you in the right direction.

Lastly, I would consider renaming this repo to `format-preserving-yaml` or `fpy` (or another name), since it now sounds like this is a tool that formats YAML, which it is clearly not.

**Comment by wisn** [comment]
@jaspervdj I have renamed the repository. Noted. Please wait until I pushed my code.

**Comment by NorfairKing** [comment]
> Ah, for the correctness part, is testing with HSpec enough? When heard something like "correctness", I always think about something like formal verification.

Testing is more cost-effective than formal verification, especially if you make heavy use of property tests.
See [validity](https://github.com/NorfairKing/validity) for some nice examples of cheap property tests.

**Comment by wisn** [comment]
Thanks @NorfairKing for the feedback and the reference as well!
